version: "3.8"
services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env  # Load environment variables from .env file
    environment:
      - DB_HOST=localhost
      - PORT=3000 # Use the PORT variable from .env
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
    depends_on:
      - redis
    ports:
      - "3000:3000"  

  redis:
    image: redis:latest
    ports:
      - "6379:6379" 
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      retries: 3
      timeout: 5s