name: Node.js CI/CD to Docker Hub

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: test_db
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install
      working-directory: ./server

    - name: Log in to Docker Hub
      run: echo "${{ secrets.PERSONALACESSTOKEN }}" | docker login -u "${{ secrets.USERNAME }}" --password-stdin

    - name: Build Docker image
      run: docker build -t oiltom/express-sequelize:latest .

    - name: Push Docker image to Docker Hub
      run: docker push oiltom/express-sequelize:latest
